### PR TITLE
[SPE-9] Chore: create a boilerplate project for backend 

### PR DESCRIPTION
**Pull request by khishh**
## Create a boilerplate project for the backend

Create the starting point for the NestJS backend project with graphql and prisma.

### Type of Change

- [ ] New Feature
- [ ] Bug Fix
- [ ] Refactoring
- [ ] Optimization
- [ ] Documentation Update
- [ ] DevOps
- [x] Chore

### Checklist (delete irrelevant items)

- [ ] I have added necessary documentation.
- [x] I have followed coding standards and best practices.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have updated the relevant tests if needed.
- [x] My changes generate no new warnings or errors.
- [ ] I have manually tested my changes.

### CODE REVIEW

**Review by m-sekander — COMMENTED** [review]
Can we switch .prettierrc key singleQuote to false? I think during one of my learning ticket's reflections, Youssef said to use double quotes as much as possible and single quotes only if necessary. Can you confirm @YoussefLaunchUp, maybe I misunderstood.

**Comment by YoussefLaunchUp** [comment]
> Can we switch .prettierrc key singleQuote to false? I think during one of my learning ticket's reflections, Youssef said to use double quotes as much as possible and single quotes only if necessary. Can you confirm @YoussefLaunchUp, maybe I misunderstood.

@m-sekander This is dependent on the team, as long as there is consistency (project wide) then that is the important part

**Review by YoussefLaunchUp — CHANGES_REQUESTED** [review]
I would change the boilerplate to be for graphql instead of rest since that's what the project will be using. (no point merging in rest boiler plate)

**Review by YoussefLaunchUp — APPROVED** [review]
Great work, in the future it might be better to name the example code something more descriptive (such as example)

**Review by m-sekander — APPROVED** [review]
LGTM!

**Pull request merged**
